custom/authenticate/urls.py
from django.urls import path

from. import views
app_name="authenticate"

urlpatterns=[
    path('',views.home,name="home"),
    path('Signup',views.signup,name="signup"),
    path('Login',views.login,name="login"),
    path('User',views.userhome,name="user"),
    path('activate_eamil/<uidb64>/<token>/<res>/',views.activate,name="activate"),
    path('logout',views.logout,name="logout"),
    path('verify',views.verifymail,name="verify"),
    path('User/changePassword',views.changepassword,name="chnage"),
    path('User/final',views.final,name="final"),
    path('User/forgot',views.forgot,name="forgot"),
    path('User/reset_password',views.resetpassword,name="resetpassword"),
     path('user/create_new_password/<uidb64>/<token>/<res>/',views.createnewpassword,name="newpassword"),
    path('chnageit',views.changeit,name="passchange"),

]

custom/custom/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from custom import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('CUSTOM/', include('authenticate.urls', namespace="authenticate")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

custom/authenticate/models.py
from djongo import models
from django.db.models.signals import post_save
from django.utils.timezone import datetime
# Create your models here.

class Account(models.Model):
    First_name=models.CharField(max_length=50)
    Last_name=models.CharField(max_length=50)
    Username=models.CharField(max_length=50,unique=True)
    Emailaddress=models.EmailField(max_length=50,unique=True)
    Password=models.CharField(max_length=50)
    created_on=models.DateTimeField(auto_now_add=True,editable=False)

class AccountDetail(models.Model):
    account=models.OneToOneField(Account,on_delete=models.CASCADE)
    reset=models.CharField(max_length=200)
    verify=models.CharField(max_length=200)
    reset_time=models.DateTimeField(default=datetime.now())
    verify_time=models.DateTimeField(default=datetime.now())
    verify_account=models.BooleanField(default=False)
    def update_account(sender,**kwargs):
        AccountDetail.objects.create(account=kwargs['instance'])
    post_save.connect(update_account,sender=Account)

class Session(models.Model):
    user_id=models.PositiveIntegerField(default=0)
    session_key=models.CharField(max_length=50)
    session_id=models.CharField(max_length=100)

custom/authenticate/views.py
import json
import os
import random
import string
from datetime import timedelta

import requests
from cryptography.fernet import Fernet
import custom.settings
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.timezone import datetime

from custom import settings
from .models import Session, Account, AccountDetail

# Create your views here.
cipher_suite = Fernet(settings.ENCRYPT_KEY3)
c_suite=Fernet(settings.ENCRYPT_KEY4)
c_suite2=Fernet(settings.ENCRYPT_KEY)
def home(request):
    return render(request,'home.html',locals())

def signup(request):
    if not request.session.session_key:
        request.session.save()
    s=request.session._session_key
    k=findkey(s)
    if k is not None:
        if Account.objects.filter(pk=k).exists():
            return redirect('authenticate:user')
    username=request.POST.get("user")
    if username is not None:
        clientKey=request.POST['g-recaptcha-response']
        secretKey=os.getenv('secretKey')
        captchadata={
        'secret':secretKey,
        'response':clientKey
        }
        r=requests.post('https://www.google.com/recaptcha/api/siteverify',data=captchadata)
        response=json.loads(r.text)
        verify=response['success']
        if verify==False:
            return render(request,'signup.html',{'error_message67':"error"})
        password=request.POST.get('pass')
        f_name=request.POST.get('fname')
        l_name=request.POST.get('lname')
        email=request.POST.get('email')
        if Account.objects.filter(Username=username).exists():
            return render(request,'signup.html',{'u':username,'error':'username already exists'})
        if Account.objects.filter(Emailaddress=email).exists():
            return render(request,'signup.html',{'e':email,'error_':'Email already exists'})
        Account.objects.create(First_name=f_name,Last_name=l_name,Username=username,Emailaddress=email,Password=make_password(password))
        return redirect('authenticate:login')
    return render(request,'signup.html',locals())

def login(request):
    if not request.session.session_key:
        request.session.save()
    s=request.session._session_key
    k=findkey(s)
    if k is not None:
        if Account.objects.filter(pk=k).exists():
            return redirect('authenticate:user')
            #return redirect('accounting:userhome')
    username=request.POST.get("userid")
    passwordgiven=request.POST.get("psw")
    if username is not None:

        clientKey=request.POST['g-recaptcha-response']
        secretKey=os.getenv('secretKey')
        captchadata={
        'secret':secretKey,
        'response':clientKey
        }
        r=requests.post('https://www.google.com/recaptcha/api/siteverify',data=captchadata)
        response=json.loads(r.text)
        verify=response['success']
        if verify==False:
            return render(request,'login.html',{'error_message67':"error"})
        try:
            account=Account.objects.get(Username=username)
            k=check_password(passwordgiven,account.Password)
            if k is True:
                ac_id=str(account.id)
                create_session(s,ac_id)
                return redirect('authenticate:user')
            else:
                return render(request,'login.html',{'error_message':'wrong password'})
        except:
            return render(request,'login.html',{'u_message':'wrong username or password'})
    else:
        return render(request,'login.html',locals())

def findkey(s):
    if Session.objects.filter(session_key=s).exists():
        session_get=Session.objects.get(session_key=s)
        email_id=session_get.session_id
        decoded=email_id.encode()
        decoded_text = cipher_suite.decrypt(decoded)
        e=decoded_text.decode()
        return e
    else:
        return None


def create_session(s,ac_id):
    encode=ac_id.encode()
    encoded_text = cipher_suite.encrypt(b"%s"%(encode))
    encoded_email=encoded_text.decode("utf-8")
    if Session.objects.filter(session_key=s).exists():
        return None
    else:
        Session.objects.create(user_id=ac_id,session_id=encoded_email,session_key=s)
def userhome(request):
    if not request.session.session_key:
        request.session.save()
    s=request.session._session_key
    k=findkey(s)
    if k is None:
        return redirect('authenticate:login')
    a=Account.objects.get(pk=k)
    ac=AccountDetail.objects.get(account=k)
    para={'name':a.First_name,'username':a.Username,'email':a.Emailaddress,'c':a.created_on,'t':ac.verify_account,'id':k}
    return render(request,'user.html',para)

def verifymail(request):
    t=request.POST.get('type')
    if t=="start":
        if not request.session.session_key:
            request.session.save()
        s=request.session._session_key
        k=findkey(s)
        if k is None:
            return redirect('authenticate:login')
        a=Account.objects.get(pk=k)
        ac=AccountDetail.objects.get(account=k)
        if ac.verify_account==True:
                data={
                    'done':'given'
                }
                return JsonResponse(data)
        ids=str(a.id)
        encoded_id=ids.encode()
        encoded_id_text=c_suite.encrypt(b"%s"%(encoded_id))
        encoded_id=encoded_id_text.decode("utf-8")
        ac_detail=AccountDetail.objects.filter(account=ids)
        res = ''.join(random.choices(string.ascii_uppercase +
                            string.digits, k = 9))
        res_make=make_password(res)
        ac_detail.update(verify_time=datetime.now(),verify=res_make)
        current_site=get_current_site(request)
        message=render_to_string('account_activation_eamil.html',{
                'user':a,
                'domian':current_site.domain,
                'name':current_site.name,
                'uid':encoded_id,
                'token':account_activation_token.make_token(a),
                'res':res,
            })
        email=a.Emailaddress
        subject="Your activation link for connect"
        send_mail(subject,message,EMAIL_HOST_USER,[email], fail_silently = False)
        #print(message)
        data={
                    'is_taken':'Log in'
                }
        return JsonResponse(data)
    else:
        return HttpResponse("Invalid Link")
def activate(request, uidb64, token,res):
    try:
        decoded=uidb64.encode()
        decoded_text = c_suite.decrypt(decoded)
        e=decoded_text.decode()
        a=Account.objects.get(pk=e)
        user=a
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None
    from custom.authenticate.tokens import account_activation_token
    if user is not None and account_activation_token.check_token(a, token):
        user_id=user.id
        account=AccountDetail.objects.filter(account=user_id)
        acc=AccountDetail.objects.get(account=user_id)
        if acc.verify_account==True:
            return HttpResponse("%s\nYour account already verified<br>")
        check=check_password(res,acc.verify)
        t=acc.verify_time
        tim=datetime.now(timezone.utc)
        times=tim+timedelta(hours=5.5)
        diff=times-t
        minutes=divmod(diff.seconds,60)
        m=minutes[0]
        if m>30:
            return HttpResponse("Activation link is invalid<br>")
        if check==True:
            account.update(verify_account=True,verify=None)
            return HttpResponse("Your email verified now<br>")
        else:
            return HttpResponse("Your link is invalid<br>")
    else:
        return HttpResponse('Activation link is invalid!')



def logout(request):
    name=request.POST.get('name')
    if name=="start":
        if not request.session.session_key:
                request.session.save()
        s=request.session._session_key
        if Session.objects.filter(session_key=s).exists():
            s=Session.objects.filter(session_key=s)
            s.delete()
            data={
                'is_done':'ok'
            }
            return JsonResponse(data)
    else:
        return HttpResponse("Invalid Link")

def changepassword(request):
    if not request.session.session_key:
            request.session.save()
    s=request.session._session_key
    k=findkey(s)
    if k is None:
        return redirect('authenticate:login')
    a=Account.objects.get(pk=k)
    ac=AccountDetail.objects.get(account=k)
    para={'name':a.First_name,'username':a.Username,'email':a.Emailaddress,'c':a.created_on,'t':ac.verify_account,'id':k}
    return render(request,'change.html',para)


def final(request):
    if request.method=="POST":
        i=request.POST.get("id")
        a=Account.objects.get(pk=i)
        ac=AccountDetail.objects.get(account=i)
        old=request.POST.get('opass')
        passw=request.POST.get('pass')
        k=check_password(old,a.Password)
        if k is True:
            para={'name':a.First_name,'username':a.Username,'email':a.Emailaddress,'c':a.created_on,'t':ac.verify_account,'id':i}
            acco=Account.objects.filter(pk=i)
            acco.update(Password=make_password(passw))
            return redirect('authenticate:user')
        else:
            para={'name':a.First_name,'username':a.Username,'email':a.Emailaddress,'c':a.created_on,'t':ac.verify_account,'id':i,'error':'error'}

        return render(request,'change.html',para)
    else:
        return redirect('authenticate:chnage')

def forgot(request):
    return render(request,'forgot.html',locals())
def resetpassword(request):
    k=request.POST.get('type')
    if k=='start':
        email=request.POST.get('email')
        if Account.objects.filter(Emailaddress=email).exists():

custom/authenticate/templates/account_activation_eamil.html
{% autoescape off %}
Hello
{{user.username}}
Please copy and paste and search for confirmation:
Valid for only 30 Minutes:

http://{{name}}{{ domain }}{% url 'authenticate:activate' uidb64=uid token=token res=res%}
{% endautoescape %}

custom/authenticate/templates/change.html
{%extends 'user.html'%}
{%block body%}
<form method="post" name="My" action="{%url 'authenticate:final'%}" onsubmit="return validateForm();">
    {%csrf_token%}
    <input type="hidden" name="id" value="{{id}}">
<div class="form-group w-50">
    <label for="opass">Old Password</label>
    <input type="password" class="form-control" id="opass" name="opass" placeholder="Old Password"  required>
  </div>
  <div class="form-group w-50">
    <label for="pass">New Password</label>
    <input type="password" class="form-control" id="pass" name="pass" placeholder="Password" pattern="(?=.*[$@$#!%?&.])(?=.*\d)(?=.*[aA-zZ]).{8,}" required>
    <small style="color: red">Must Contain:-Characters Length(8),One Special Character($@$#!%?&.),At Least-One Number,Alphabet,</small>
  </div>
  <div class="form-group w-50">
    <label for="pass2">Retype Password</label>
    <input type="password" class="form-control" id="pass2" name="pass2" placeholder="Password"  required>
  </div>
<button type="submit" class="btn btn-primary">Change Password</button>
</form>
{%if error%}
<script>
    alert("Old password not Matched");
</script>
{%endif%}
<script>
   function validateForm() {
  var x = document.forms["My"]["pass"].value;
  var y = document.forms["My"]["pass2"].value;

  if (x!=y) {
    alert("Password Not Matched");
    return false;
  }

}

</script>
{%endblock%}

custom/authenticate/templates/forgot.html
{%extends 'home.html'%}
{%block body%}
<meta name="_token" content="{{ csrf_token }}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<form  method="post" id="form" >
{%csrf_token%}
    <div class="form-group w-50">
    <label for="email">Email Address</label>
    <input type="email" class="form-control" name="email" id="email" placeholder="Email" required>
  </div>
    <button type="submit" class="btn btn-danger">Reset Password</button>
</form>
<script>
    $('#form').on('submit', function(e){

e.preventDefault();

  $.ajax({
       type : "POST",
       url: "{%url 'authenticate:resetpassword'%}",
       data: {
       type:'start',
        email: $('#email').val(),
        csrfmiddlewaretoken:$('meta[name="_token"]').attr('content')


       },

       success: function(data){
       if(data.is_taken){
       alert('password reset link send to your mail');
       }
       if(data.is_provider){
       alert('Sorry due to some security risk we dont reset your password');
       }
       if(data.is_created){
          alert("You are not a valid user");
           }/* response message */
       },

       failure: function() {
            alert("Some error......");
       }


   });


        });

</script>
{%endblock%}

custom/authenticate/templates/home.html
<!doctype html>
<html lang="en">

<head>
{%load staticfiles%}
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>
<style>
    body{
    background-image: url("{% static 'images/backimage.jpg'%}");
    background-repeat: no-repeat;
  }
  .navbar-inner {
    background:transparent;
}
</style>
<body>
<nav class="navbar navbar-expand-lg bg-transparent navbar-dark">
  <div class="container">
    <a class="navbar-brand" href="#" >CUSTOM</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto" >

        <li class="nav-item active" >
          <a class="nav-link" href="{%url 'authenticate:home'%}">Home</a>
        </li>
        <li class="nav-item" >
          <a class="nav-link" href="{%url 'authenticate:login'%}" >Login</a>
        </li>
        <li class="nav-item" >
          <a class="nav-link" href="{%url 'authenticate:signup'%}" >New User</a>
        </li>

      </ul>
    </div>
  </div>
</nav>


<center style="position:relative;top:50px;;color:white;">
    {%block body%}
    <H1>welcome to our dashboard</H1>
    <H2>Made By monika</H2>
    <h3>On:-23/07/2020</h3>
    {%endblock%}
</center>
</body>

custom/authenticate/templates/login.html
{%extends 'home.html'%}
{%block body%}
 <script src="https://www.google.com/recaptcha/api.js" async defer></script>
<form method="post" action="{%url 'authenticate:login'%}">
{%csrf_token%}
    <div class="form-group w-50">
    <label for="uname">Username</label>
    <input type="text" class="form-control" name="userid" id="uname" placeholder="Username" required>
  </div>

  <div class="form-group w-50">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" name="psw" id="exampleInputPassword1" placeholder="Password" required>
  </div>
    <div class="g-recaptcha" data-sitekey="6Lcpo60ZAAAAAJJe2TEsBI8IGed9EkV8_T-pBgSg" ></div>
    {%if error_message%}
    <small style="color: red">{{ error_message}}</small><br>
    {%endif%}

    {%if u_message%}
    <small style="color: red">{{ u_message}}</small><br>
    {%endif%}
{%if error_message67%}
    <script>
        alert("Recaptcha Fail");
    </script>
    {%endif%}

  <button type="submit" class="btn btn-primary">Login</button>
</form>
<br>
<a href="{%url 'authenticate:forgot'%}" class="btn btn-danger">Forgot Password</a>
{%endblock%}

custom/authenticate/templates/password.html
{%extends 'home.html'%}
{%block body%}

<meta name="_token" content="{{ csrf_token }}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

 <form  method="post"  name="My" action="{%url 'authenticate:passchange'%}" onsubmit="return validateForm();">
{%csrf_token%}
    <label class="headlabel">Reset Your Password</label>
       <div class="form-group">
      <input type="hidden" id="user_id" name="id" value="{{user_id}}" >
      <input type="hidden" id="res" name="res" value="{{res}}">
    </div>
     <div class="form-group w-50">
    <label for="pass">New Password</label>
    <input type="password" class="form-control" id="pass" name="pass" placeholder="Password" pattern="(?=.*[$@$#!%?&.])(?=.*\d)(?=.*[aA-zZ]).{8,}" required>
    <small style="color: red">Must Contain:-Characters Length(8),One Special Character($@$#!%?&.),At Least-One Number,Alphabet,</small>
  </div>
  <div class="form-group w-50">
    <label for="pass2">Retype Password</label>
    <input type="password" class="form-control" id="pass2" name="pass2" placeholder="Password"  required>
  </div>
<button type="submit" name="type" value="start" class="btn btn-primary">Change Password</button>


  </form>
{%if e%}
<script>
    alert('password reset');
    window.location.href="{%url 'authenticate:login'%}";
</script>
{%endif%}
<script>
    function validateForm() {
  var x = document.forms["My"]["pass"].value;
  var y = document.forms["My"]["pass2"].value;


  if (x!=y) {
   alert("Password Not Matched");
    return false;
  }
</script>

{%endblock%}

custom/authenticate/templates/password_reset_email.html
{% autoescape off %}
Hello
{{user.username}}
Please copy and paste and search for confirmation:
Valid for only 30 Minutes:

http://{{name}}{{ domain }}{% url 'authenticate:newpassword' uidb64=uid token=token res=res%}
{% endautoescape %}

custom/authenticate/templates/user.html
<!doctype html>
<html lang="en">

<head>
{%load staticfiles%}
    <meta name="_token" content="{{ csrf_token }}">
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<style>
    body{
    background-image: url("{% static 'images/backimage.jpg'%}");
    background-repeat: no-repeat;
  }
  .navbar-inner {
    background:transparent;
}
</style>
<body>
<nav class="navbar navbar-expand-lg bg-transparent navbar-dark">
  <div class="container">
    <a class="navbar-brand" href="{%url 'authenticate:home'%}" >CUSTOM</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto" >

        <li class="nav-item active" >
          <a class="btn btn-danger" href="{%url 'authenticate:user'%}">Home</a>
        </li>
        <li class="nav-item" >
          <button onclick="logout()" class="btn btn-danger">Logout</button>
        </li>
          <li class="nav-item" >
          <a class="btn btn-danger" href="{%url 'authenticate:chnage'%}">ChangePassword</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<center style="position:relative;top:50px;;color:white;">

    <H1>Hello:-{{name}}</H1>
    <H2>{{username}}</H2>
    <h3>{{email}}</h3>
    <h4>{{c}}</h4>
    {%if t is False%}
    <h2><button value="{{id}}" onclick="getemail()" class="btn btn-danger">Verify Email</button></h2>
    {%endif%}
    {%block body%}
    {%endblock%}
</center>
<script>
    function logout(){
        $.ajax({

type: 'POST',

url: '{%url 'authenticate:logout'%}',


data: {name:'start' ,csrfmiddlewaretoken:$('meta[name="_token"]').attr('content')}

}).done(function(data){
window.location.href="{%url 'authenticate:login'%}";
}).fail(function() {

alert( "Posting failed." );

});

    }
function getemail(){
$.ajax({

                type: 'POST',

                url: '{%url 'authenticate:verify'%}',

                data: {type:'start',csrfmiddlewaretoken:$('meta[name="_token"]').attr('content')}

            }).done(function(data){

              if(data.is_taken){

              alert("Email Send");
                return false;
              }
              if(data.done){

              alert("Email Verfication Alreday done");
                return false;
              }

            }).fail(function() {

                alert( "Posting failed." );
                return false;

            });


}

</script>
</body>